import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';
import { initializeApp } from 'firebase/app';
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw';

// ──────────────────────────────────────────────
// 1. Core PWA setup
// ──────────────────────────────────────────────

// Clean up old caches from previous versions
cleanupOutdatedCaches();

// Precache the static assets generated by Vite at build time
precacheAndRoute(self.__WB_MANIFEST);

// Claim clients immediately so the SW controls the page ASAP
self.skipWaiting();
clientsClaim();

// ──────────────────────────────────────────────
// 2. Navigation fallback – CRITICAL for SPA
// ──────────────────────────────────────────────
// When the user navigates (e.g. comes back from Paytm, or opens a deep link),
// always serve index.html from cache-first-then-network so the SPA router can handle it.
// Without this, returning from external apps shows a white screen.

const navigationHandler = new NetworkFirst({
    cacheName: 'navigations',
    plugins: [
        new CacheableResponsePlugin({ statuses: [200] }),
    ],
});

const navigationRoute = new NavigationRoute(navigationHandler, {
    // Don't intercept API calls, Netlify function calls, Supabase proxy, Clerk handshakes, or Razorpay callbacks
    denylist: [
        /^\/api\//,
        /^\/_netlify\//,
        /^\/\.netlify\//,
        /^\/supabase\//,
        /\?.*__clerk_handshake/,
        /razorpay/i,
        /\/payments\//,
    ],
});
registerRoute(navigationRoute);

// ──────────────────────────────────────────────
// 2b. NEVER intercept Razorpay or UPI payment URLs
// ──────────────────────────────────────────────
// On iOS standalone PWA, the service worker can intercept Razorpay
// redirect callbacks, causing the raw URL to show instead of
// completing the payment. Force all Razorpay traffic to go directly
// to the network.
registerRoute(
    ({ url }) =>
        url.hostname.includes('razorpay') ||
        url.hostname.includes('razorpay.com') ||
        url.hostname.includes('api.razorpay.com') ||
        url.pathname.includes('razorpay') ||
        url.pathname.includes('/payments/'),
    new NetworkFirst({
        cacheName: 'razorpay-bypass',
        plugins: [
            new CacheableResponsePlugin({ statuses: [200] }),
            new ExpirationPlugin({ maxEntries: 5, maxAgeSeconds: 60 }),
        ],
    }),
);

// ──────────────────────────────────────────────
// 3. Runtime caching for JS/CSS assets
// ──────────────────────────────────────────────
// Use StaleWhileRevalidate for hashed assets so users always get
// cached content fast, while the cache updates in the background.
registerRoute(
    ({ request, url }) =>
        url.origin === self.location.origin &&
        (request.destination === 'script' || request.destination === 'style'),
    new StaleWhileRevalidate({
        cacheName: 'static-assets',
        plugins: [
            new CacheableResponsePlugin({ statuses: [200] }),
            new ExpirationPlugin({
                maxEntries: 60,
                maxAgeSeconds: 24 * 60 * 60, // 1 day – stale hashes auto-expire
            }),
        ],
    }),
);

// ──────────────────────────────────────────────
// 4. NEVER cache Clerk SDK requests
// ──────────────────────────────────────────────
// Clerk loads its JS from its own CDN. If the SW caches it and later
// serves a stale version the SDK throws "Failed to load Clerk".
registerRoute(
    ({ url }) =>
        url.hostname.includes('clerk') ||
        url.hostname.includes('clerk.com') ||
        url.hostname.includes('clerk.dev') ||
        url.hostname.includes('accounts.dev'),
    new NetworkFirst({
        cacheName: 'clerk-sdk',
        plugins: [
            new CacheableResponsePlugin({ statuses: [200] }),
            new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 60 * 5 }), // 5 min max
        ],
    }),
);

// ──────────────────────────────────────────────
// 5. Image caching (logos, PWA icons, etc.)
// ──────────────────────────────────────────────
registerRoute(
    ({ request }) => request.destination === 'image',
    new StaleWhileRevalidate({
        cacheName: 'images',
        plugins: [
            new CacheableResponsePlugin({ statuses: [200] }),
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
            }),
        ],
    }),
);

// ──────────────────────────────────────────────
// 6. Firebase Cloud Messaging (background)
// ──────────────────────────────────────────────
try {
    const firebaseConfig = {
        apiKey: "AIzaSyCV97bFUFLu9I2Mb0rCVpcalJg0F-nrZ9k",
        authDomain: "canteenqnotification-b61e0.firebaseapp.com",
        projectId: "canteenqnotification-b61e0",
        storageBucket: "canteenqnotification-b61e0.firebasestorage.app",
        messagingSenderId: "11504592565",
        appId: "1:11504592565:web:1bda9c21f6790e981180fc",
        measurementId: "G-84EZWKDWS1"
    };

    const app = initializeApp(firebaseConfig);
    const messaging = getMessaging(app);

    onBackgroundMessage(messaging, (payload) => {
        console.log('[sw.js] Received background message ', payload);
        const notificationTitle = payload.notification?.title || 'New Notification';
        const notificationOptions = {
            body: payload.notification?.body,
            icon: '/pwa-192x192.png'
        };

        self.registration.showNotification(notificationTitle, notificationOptions);
    });
} catch (error) {
    console.error('Error in Service Worker Firebase setup:', error);
}
